### PR TITLE
Updating 'Projects' Module to Reflect New GitHub Project Rules

### PR DESCRIPTION
**Pull request by njlyon0**
Per our conversation in the team meeting last week, updated the "projects" module to better reflect GitHub's prioritization of "Projects" over the now-superseded "Projects (Classic)". Also increased emphasis on using projects and decreased emphasis on the difference between a User-owned and Org-owned project (seems like most working groups would use an LTER org-owned project anyway).

### CODE REVIEW

**Comment by angelchen7** [comment]
Thanks for your edits @njlyon0 !! And thanks for your patience as I get back from working with the working group last week 😅 

The revised Projects page looks great! I do have some comments:

1. Should we revise this line in the Learning Objectives, "Summarize the different features of projects created within (A) organizations, (B) users, and (C) repositories"? Since we don't mention repo-specific projects anymore, we should rephrase that line. 
2. In the "Using Projects" section maybe we can replace the first screencap with an updated one showing your current "[Scientific Computing - Lyon](https://github.nceas.ucsb.edu/orgs/LTER/projects/8)" project. The old screencap is still showing your old classic project that doesn't have the "Views" that your new one has now 🤔  I think it would be nice to emphasize that the newer Projects have different Views
Screen Shot 2024-01-29 at 4 18 03 PM

And now that I'm thinking about it, I'm wondering if it's worth it to mention the different Views that the newer Projects have somewhere in the "Using Projects" section 🤔 because I know I was confused by the different options when I first used them.  

3. In the "Project Ownership" section, I think it would be nice to replace the first screencap in that section to one that shows exactly where the "New Project" button would be
Screen Shot 2024-01-29 at 4 27 43 PM

4. Lastly I feel the order of "Using Projects" and "Project Ownership" can be switched. What do you think?

**Comment by njlyon0** [comment]
Hey @angelchen7 ! How are those edits looking! I decided it was simplest to address the 'view' thing by just adding a new section and associated learning objective. I've made all of your other edits (I think--let me know if I missed any!) but feel free to weigh in with other edits. I'm feeling a lot better about this module now that we're upgrading away from "Projects (classic)"

**Review by angelchen7 — APPROVED** [review]
Great job Nick! I really like the new section on Views and I didn't see anything else other than a typo, which I fixed. It looks good to go!! Feel free to merge the PR

**Comment by njlyon0** [comment]
Excellent, thanks for catching that issue!

**Pull request merged**
